# Избранное
## Добавить в избранное

POST http://localhost:31337/favorites/add HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuc0BvdmVybG9vay5uZXQiLCJuYW1lIjoiSmFjayIsImlkIjoiNjU0MDA4YWJlNDUyYjgyNWY5ZjY4YTEyIiwiaWF0IjoxNjk5MzYwMTkyLCJleHAiOjE2OTk1MzI5OTJ9.-YLEjns8JFBMZfgxfq4RHnwYrzexPFqm_W7kaAaoR9g

{
  "offerId": "654a2f1ce99efcefbd871dee"
}

###

## Удалить из избранного

POST http://localhost:31337/favorites/remove HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuc0BvdmVybG9vay5uZXQiLCJuYW1lIjoiSmFjayIsImlkIjoiNjU0MDA4YWJlNDUyYjgyNWY5ZjY4YTEyIiwiaWF0IjoxNjk5MzYwMTkyLCJleHAiOjE2OTk1MzI5OTJ9.-YLEjns8JFBMZfgxfq4RHnwYrzexPFqm_W7kaAaoR9g

{
  "offerId": "654a2f1ce99efcefbd871dee"
}

###