# Пользователи
## Создать нового пользователя

POST http://localhost:31337/users/register HTTP/1.1
Content-Type: application/json

{
  "name": "Jack Torrance",
  "email": "torans@overlook.net",
  "avatar": "torrance.png",
  "password": "shining",
  "userType": "pro"
}

###

## Авторизовать пользователя

POST http://localhost:31337/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "torans@overlook.net",
  "password": "shining"
}

###

## Отправить изображение

POST http://localhost:31337/users/62823cb2c5a64ce9f1b50eb6/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="screen.png"
Content-Type: image/png

# < /Users/spider_net/Desktop/screen.png
# ------WebKitFormBoundary7MA4YWxkTrZu0gW--

##
