# Пользователи
## Создать нового пользователя

POST http://localhost:31337/users/register HTTP/1.1
Content-Type: application/json

{
  "name": "Jack Torrance",
  "email": "torans@overlook.net",
  "avatar": "torrance.png",
  "userType": "pro",
  "password": "shining"
}

###

## Авторизовать пользователя

POST http://localhost:31337/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "torans@overlook.net",
  "password": "260ad7c41e14fa667fe9215b91b6ef6f42dd44efdaf7f41972967a2c9cca98d3"
}

###

POST http://localhost:31337/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "tom@gmail.com",
  "password": "4a83854cf6f0112b4295bddd535a9b3fbe54a3f90e853b59d42e4bed553c55a4"
}

###

## Отправить изображение

POST http://localhost:31337/users/62823cb2c5a64ce9f1b50eb6/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="screen.png"
Content-Type: image/png


< /Users/uriy/Desktop/_DSC5610.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

## Проверить токен пользователя
GET http://localhost:31337/users/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuc0BvdmVybG9vay5uZXQiLCJpZCI6IjY0NzBiYzM4M2UzMGRiNjc5ZGZhYzJkMiIsImlhdCI6MTY4NTk3NTQ4MiwiZXhwIjoxNjg2MTQ4MjgyfQ.Gq2-B1egouAnMxmXlR2ElVT6wCa97PS6lxzVI8LnGvo

###